

#raw files
data_raw:
    file1: "../data/raw/df_final_demo.txt"
    file2: "../data/raw/df_final_experiment_clients.txt"
    file3: "../data/raw/df_final_web_data_pt_1.txt"
    file4: "../data/raw/df_final_web_data_pt_2.txt"

#clean_files

data_clean:
    user_data: "../data/clean/user_data.csv"
    user_logs: "../data/clean/user_logs.csv"

